### ISSUE TITLE
The Narrate feature doesn't automatically play when entering Reader View mode if the user previously interacted with the survey.

### ISSUE THREAD

**Issue by Softvision-PatriciuPop** [mozilla/firefox-narrate-experiment#10]
[Affected versions]:
- Firefox Dev Edition Version 66.0b9, Build ID 20190218131312
- Firefox Release Unbranded Version 65.0.1, Build ID 20190211233335

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- The firefox_listen_study-0.3 build is installed.
- Enrolled in the Feature- passive or feature-active branch.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites and navigate to a Wikipedia article.
2. Click the "Toggle Reader View" button.
3. Click the "Would you like to rate this listening experience?" button.
4. Navigate to the previously opened article and stop the playback.
5. Navigate to a new article and click the "Toggle Reader View" button.
6. Observe the behavior.

[Expected result]:
- The Wikipedia article is loaded in the Reader View mode and the playback automatically starts.

[Actual result]:
- The Wikipedia article is loaded in the Reader View mode and the Narrate control menu is closed, the playback doesn't start.

[Notes]:
- I have attached a screen recording of the issue:
![fxnarrate_survey](https://user-images.githubusercontent.com/40393891/53094939-235e7b00-3524-11e9-944e-714c006db66c.gif)

**Comment by awallin** [comment]
@Gozala Can you take a look at this issue?

**Comment by Gozala** [comment]
Will do

**Comment by Softvision-PatriciuPop** [comment]
I have verified that this issue is no longer reproducible using firefox-listen-study@shield.mozilla.org-0.4-signed-testing.xpi on Windows 10 x64 and Mac 10.14.2 using Firefox Unbranded Beta Version 66.0b12, Build ID 20190228180200.
