### ISSUE TITLE
The "Listen to this article" name is wrongly displayed instead of "Start Listening" for the blue button in the "Narrate" door hanger

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [mozilla/firefox-narrate-experiment#11]
**[Notes]:**
- According to the [PHD](https://docs.google.com/document/d/1Tk6igTU5eaa8v31qkS8W18520SE_iEY4QUzvvVNS1tU/edit) document the name of the "Button B" blue button should be "Start Listening".

**[Affected versions]:**
- Firefox 65 Unbranded
- Firefox 66.0b9 Dev. Edition

**[Affected Platforms]:** 	 	
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have a new Firefox profile with the latest version of the "Firefox Narrate" add-on (0.3) custom build installed through "about:debugging".
- You are enrolled in the "feature-active" branch.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites and navigate to the "https://en.wikipedia.org/wiki/Main_Page" website.
2. Observe the blue button displayed in the door hanger.

**[Expected result]:**
- The name off the blue button is "Start Listening".

**[Actual result]:**
- The name of the button is "Listen to this article".

**[Additional Notes]:**
- Attached are screen recording of the issue:
![wrongbutton](https://user-images.githubusercontent.com/40061643/53099144-d4b5de80-352d-11e9-9fcf-192a75612e82.gif)

**Comment by awallin** [comment]
@Gozala Can you make this change when you update when the doorhanger appears?

**Comment by Gozala** [comment]
> @Gozala Can you make this change when you update when the doorhanger appears?

Sure, I'll update label

**Comment by Softvision-RemusDranca** [comment]
I have verified this issue with the latest Narrate version (0.4-signed-testing), and it's no longer reproducible.
Tested on Windows 10 and Mac 10.14 using Firefox Unbranded Beta Version 66.0b12, Build ID 20190228180200.
