### ISSUE TITLE
The message displayed in the door hanger's body wrongly suggests that the feature can read any page on the internet

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [mozilla/firefox-narrate-experiment#12]
**[Affected versions]:**
- Firefox 65 Unbranded
- Firefox 66.0b9 Dev. Edition

**[Affected Platforms]:** 	 	
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have a new Firefox profile with the latest version of the "Firefox Narrate" add-on (0.3) custom build installed through "about:debugging".
- You are enrolled in the "feature-active" branch.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites and navigate to the "https://en.wikipedia.org/wiki/Main_Page" website.
2. Observe the message displayed in the door hanger's body.

**[Expected result]:**
- The message suggests that almost all the page's on the internet can be read, since the "Narrate" button is not displayed on all websites.

**[Actual result]:**
- The "Firefox can read you any page on the internet." message is displayed.

**[Notes]:**
- Attached are screen shot of the issue:
![doorhanger](https://user-images.githubusercontent.com/40061643/53103413-47c35300-3536-11e9-88c6-46d49b26b16a.png)

**Comment by awallin** [comment]
The experiment is to understand how much interest there is to listening to web content. While it's not accurate in every case it gets the message across accurately enough for this test. Closing this issues as won't fix.
