### ISSUE TITLE
The addon is wrongly displayed on the about:addons page

### ISSUE THREAD

**Issue by Softvision-PatriciuPop** [mozilla/firefox-narrate-experiment#13]
[Notes]:
- More info about this can be found [here](https://bugzilla.mozilla.org/show_bug.cgi?id=1365349#c3).

[Affected versions]:
- Firefox Unbranded Beta Version 66.0b9, Build ID 20190218131312

[Affected Platforms]:
- All Windows
- All Linux
- All Mac

[Prerequisites]:
- The "xpinstall.signatures.dev-root" boolean pref was created with the "true" value.
- The firefox-listen-study@shield.mozilla.org-0.3-signed-testing.xpi is available.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Navigate to the about:addons page, "Extensions" section and install the add-on.
3. Refresh the page and observe the behavior.

[Expected result]:
- The page is refreshed and the add-on is not displayed in the list.

[Actual result]:
- The page is refreshed and the add-on remains displayed in the list.

[Additional Notes]:
- I have attached a screenshot of the issue:
![image](https://user-images.githubusercontent.com/40393891/53158938-6f192f00-35cd-11e9-91c6-96f4cae835e3.png)

**Comment by awallin** [comment]
@ianb Do you if add-ons for Shield experiments are suppose to be displayed in the list of extensions?

**Comment by Gozala** [comment]
I can't really test this as we need new signed copy, but I did added `hidden` flag to manifest as per [Bug 1365349](https://bugzilla.mozilla.org/show_bug.cgi?id=1365349)

**Comment by Softvision-PatriciuPop** [comment]
I have verified that this issue is no longer reproducible using firefox-listen-study@shield.mozilla.org-0.4-signed-testing.xpi on Windows 10 x64 and Mac 10.14.2 using Firefox Unbranded Beta Version 66.0b12, Build ID 20190228180200.
