### ISSUE TITLE
The add-on cannot be installed on the 65 versions of Firefox.

### ISSUE THREAD

**Issue by Softvision-PatriciuPop** [mozilla/firefox-narrate-experiment#14]
[Notes]:
- I believe this is a Firefox regression since it can be installed on newer versions or older than 65. Considering this using mozregression I found the following push log:
Last good revision: 11dd717f4a3ef27b0d64047c582c046bcd4db622
First bad revision: d2fa56922a47956d230e8e6581843fa1615282ff
Pushlog: https://goo.gl/NYKyMm
However I do not have authorization to see the bug that probably caused this issue.

[Affected versions]:
- Firefox Release Unbranded Version 65.0.1, Build ID 20190211233335
- Firefox Nightly Version 65.0a1, Build ID 20181022220734

[Affected Platforms]:
- All Windows
- All Linux
- All Mac

[Prerequisites]:
- The "xpinstall.signatures.dev-root" boolean pref was created with the "true" value.
- The firefox-listen-study@shield.mozilla.org-0.3-signed-testing.xpi is available.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites and navigate to the about:addons page, "Extensions" section.
2. Drag and Drop the .xpi file on the page's content and observe the behavior.

[Expected result]:
- The Fx Narrate add-on is installed.

[Actual result]:
- The installation confirmation doorhanger is not displayed and the add-on is not installed.

[Additional Notes]:
- I have attached a screen recording of the issue:
![fxnarrate_install](https://user-images.githubusercontent.com/40393891/53169885-3a19d600-35e7-11e9-8857-1b856535a055.gif)

**Comment by awallin** [comment]
@Gozala Can you take a look?

**Comment by Gozala** [comment]
@awallin I can try to looking what's going on, but most likely that's something on the Firefox end and not the extension side. I need the signed add-on to try it though
