### ISSUE TITLE
[Mac] Firefox Narrate wrongly reads multiple articles simultaneously

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [mozilla/firefox-narrate-experiment#15]
**[Affected versions]:**
- Firefox 66.0b9 Unbranded

**[Affected Platforms]:** 	 	
- All Mac

**[Prerequisites]:**
- Have a new Firefox profile with the latest version of the "Firefox Narrate" add-on (0.3) signed build.
- You are enrolled in the "feature-passive" or "feature-active" branch.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites and navigate to the "https://en.wikipedia.org/wiki/Main_Page" website.
2. Click the "Toggle Reader View" button from the Awesomebar. 
3. Open the same page from step 1 or a new article in a new tab.
4. Click the "Toggle Reader View" button from the Awesomebar and observe the behavior. 

**[Expected result]:**
- The Narrate view is opened and doesn't start playing.

**[Actual result]:**
- The Narrate view is opened and starts playing.

**[Notes]:**
- This issue is reproducible only on the "feature-passive" and "feature-active" branches.
- This issue is reproducible even if more then 2 websites are opened, the websites are read/played simultaneously.
- This issue is not reproducible on Windows and Linux.
- Attached is a [screen recording](https://drive.google.com/open?id=1_azx-VesXexOntn4gA2Gqh7eTXt44d78) of the issue.

**Comment by awallin** [comment]
This use case is uncommon and can be easily fixed by the user. For this experiment we can ship with the current behavior. Closing as won't fix.
