### ISSUE TITLE
The "narrate-playback" ping is not sent when the user navigates away from the page

### ISSUE THREAD

**Issue by Softvision-PatriciuPop** [mozilla/firefox-narrate-experiment#17]
[Affected versions]:
- Firefox Unbranded Beta Version 66.0b9, Build ID 20190218131312

[Affected Platforms]:
- All Windows
- All Linux
- All Mac

[Prerequisites]:
- The "xpinstall.signatures.dev-root" boolean pref was created with the "true" value.
- The firefox-listen-study@shield.mozilla.org-0.3-signed-testing.xpi is installed.
- Enrolled in the feature-passive or feature-active branch.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Navigate to a Wikipedia article and click the "Toggle Reader View" button.
3. Navigate to about:telemetry in another tab and observe the archived pings.

[Expected result]:
- The "narrate-playback" ping is sent with the "stopReason": "unload" attribute.

[Actual result]:
- Only the "narrate-enter" ping is displayed.

[Notes]:
- Navigating to another page by clicking a link from the article closes Reader View and successfully sends the ping. However according to the PHD the ping is sent when the "user navigated away" but we are not sure if the scenario described in the bug is also applicable.
- I have attached a screen recording of the issue:
![fxnarrate_navaway](https://user-images.githubusercontent.com/40393891/53182967-2d0ae000-3603-11e9-8a78-db18e0b29f1a.gif)

**Comment by Gozala** [comment]
I think current behavior is expected. Ping is send once narrate stops speaking which is either because it’s finished, paused, user navigates away or closes tab. In this case tab is still open and still voice is still speaking so no pings are expected.

**Comment by Gozala** [comment]
@awallin does above sound right to you ?

**Comment by awallin** [comment]
Correct. This behavior is as expect because the audio does not stop playing the user is potentially/probably still listening.
