### ISSUE TITLE
The "narrate-enter" ping is wrongly sent when the user clicks the "Toggle Reader View" on the control branch

### ISSUE THREAD

**Issue by Softvision-PatriciuPop** [mozilla/firefox-narrate-experiment#18]
[Affected versions]:
- Firefox Unbranded Beta Version 66.0b9, Build ID 20190218131312

[Affected Platforms]:
- All Windows
- All Linux
- All Mac

[Prerequisites]:
- The "xpinstall.signatures.dev-root" boolean pref was created with the "true" value.
- The firefox-listen-study@shield.mozilla.org-0.3-signed-testing.xpi is installed.
- Enrolled in the control branch.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Navigate to a Wikipedia article and click the "Toggle Reader View" button.
3. Navigate to about:telemetry in another tab and observe the archived pings.

[Expected result]:
- No ping is sent.

[Actual result]:
- The "narrate-enter" ping is sent.

[Notes]:
- I have attached a screen recording of the issue:
![fxnarrate_controltel](https://user-images.githubusercontent.com/40393891/53185980-cd173800-3608-11e9-81da-c173d7e3487d.gif)

**Comment by awallin** [comment]
@Gozala This is the ping to indicate the user has entered narrate so we can compare usage between the 3 versions, correct?

**Comment by Gozala** [comment]
Correct!

**Comment by awallin** [comment]
Closing as this ping is in place to measure usage of reader mode in the control version of the experiment.

**Comment by Softvision-PatriciuPop** [comment]
I understand, however the Fx Narrate Metrics Definition document states that "We do have `control` branch, however feature isn’t active for that branch so we should not see anything coming off of it." and the "narrate-enter" is one of the pings from the feature. 
Please update the documents to avoid any confusion.

**Comment by awallin** [comment]
@Softvision-PatriciuPop Can you point me to that documentation so I can update it. I've update details about the pings in the control branch on the PHD and the Experimenter.

**Comment by Softvision-PatriciuPop** [comment]
I was referring to the Fx Narrate Metrics Definition document ([link](https://docs.google.com/document/d/1dduVhtwk1FdxyWCsI_QCHQPSHHy8UpPvKOPm2mNeP3c/edit#heading=h.hhq9zhdbik9a)).
