### ISSUE TITLE
The next article is wrongly read with the default voice even if on a previous one another voice was selected

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [mozilla/firefox-narrate-experiment#19]
**[Affected versions]:**
- Firefox 66.0b9 Unbranded

**[Affected Platforms]:** 	 	
- All Windows
- All Mac

**[Prerequisites]:**
- Have a new Firefox profile on Firefox 66.0b9 Unbranded created.
- Have the "xpinstall.signatures.dev-root" boolean pref with the "true" value created.
- Have the latest version of the "Firefox Narrate" add-on (0.3) signed build installed.
- You are enrolled in the "feature-passive" or "feature-active" branch.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites and navigate to the "https://en.wikipedia.org/wiki/Main_Page" website.
2. Click the "Toggle Reader View" button from the Awesomebar. 
3. Click the "Voice" section from the door hanger and select a different voice from the one playing.
4. Close the current tab and open a new article from Wikipedia in a new tab.
5. Click the "Toggle Reader View" button from the Awesomebar. 
6. Listen to the voice reading the article.

**[Expected result]:**
- The voice that was previously selected is reading the article.

**[Actual result]:**
- The default voice is reading the article even if the voice displayed is the one previously selected. 

**[Notes]:**
- This issue is not reproducible using the default feature, the selected voice reads all new opened articles.
- The issue is also not reproducible on "control" branch. 
- Attached is a [screen recording](https://drive.google.com/file/d/1E8M_7BGR4f1nZFAX71fQV9-5XtU8Kuhu/view?usp=sharing) of the issue:

**Comment by awallin** [comment]
A very tiny number of users select a custom voice. We're safe to run this limited experiment without addressing this one.
