### ISSUE TITLE
No feedback is submitted after the rating stars are checked 

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [mozilla/firefox-narrate-experiment#24]
**[Notes]:**
- When I tested this behavior with the previous version of the add-on (v 0.3), when the rating stars where clicked, I was redirected to the "https://www.research.net/r/FRLBYR5" feedback page. Also the rating stars were not checked and the feedback button was dismissed and no longer displayed.

**[Affected versions]:**
- Firefox Beta 66.0b12 Unbranded

**[Affected Platforms]:** 	 	
- All Windows
- All Mac

**[Prerequisites]:**
- Have a new Firefox profile with the "xpinstall.signatures.dev-root" boolean pref with the "true" value created.
- Have the latest version of the "Firefox Narrate" add-on (0.4) signed build installed.
- You are enrolled in the "feature-passive" or "feature-active" branch.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites. 
2. Navigate to the "https://en.wikipedia.org/wiki/Main_Page" website.
3. Click the "Toggle Reader View" button from the Awesomebar.
4. Click the rating stars displayed in the doorhanger.
5. Observe the behavior.

**[Expected result]:**
- The rating stars are checked and the feedback is submitted or you are redirected to the feedback page.

**[Actual result]:**
- The stars are checked but nothing happens.

**[Additional Notes]:**
- Attached is a screen recording of the issue:
![checkstars](https://user-images.githubusercontent.com/40061643/53745403-a0381000-3ea7-11e9-845c-e4d81ab4723e.gif)

**Comment by awallin** [comment]
@Gozala Can you take a look?

**Comment by Softvision-PatriciuPop** [comment]
I have verified that this issue is no longer reproducible using firefox-listen-study@shield.mozilla.org-0.7-signed-testing.xpi on Windows 10 x64 and Mac 10.14.3 using Firefox Unbranded Beta Version 66.0b14, Build ID 20190307095232.
