### ISSUE TITLE
The "narrate-enter" ping is not longer sent using the 0.4 version of the add-on

### ISSUE THREAD

**Issue by Softvision-PatriciuPop** [mozilla/firefox-narrate-experiment#25]
[Affected versions]:
- Firefox Unbranded Beta Version 66.0b12, Build ID 20190228180200

[Affected Platforms]:
- All Windows
- All Mac

[Prerequisites]:
- The "xpinstall.signatures.dev-root" boolean pref was created with the "true" value.
- The firefox-listen-study@shield.mozilla.org-0.4-signed-testing.xpi is installed.
- User enrolled in the "feature-passive" or the "feature-active" branch.

[Steps to reproduce]:
- Open the browser with the profile from prerequisites.
- Navigate to a Wikipedia article and click the "Toggle Reader View" button.
- Navigate to about:telemetry in another tab and change the ping data source to "archived pings".
- Click the "Raw Data" button and observe the archived pings.

[Expected result]:
- The "narrate-enter" ping is displayed.

[Actual result]:
- No telemetry ping is sent.

[Notes]:
- All other pings are sent correctly.
- I have attached a screen recording of the issue:
![narrate-enter](https://user-images.githubusercontent.com/40393891/53806994-1fd0e800-3f57-11e9-9829-31314ba96d1e.gif)

**Comment by awallin** [comment]
@Gozala Can you take a look?

**Comment by Softvision-PatriciuPop** [comment]
I have verified that this issue is no longer reproducible using firefox-listen-study@shield.mozilla.org-0.7-signed-testing.xpi on Windows 10 x64 and Mac 10.14.3 using Firefox Unbranded Beta Version 66.0b14, Build ID 20190307095232.
