### ISSUE TITLE
[Linux] The "Listen" string overlaps with the blue headset icon 

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [mozilla/firefox-narrate-experiment#7]
**[Affected versions]:**
- Firefox 65 Unbranded
- Firefox 66.0b9 Dev. Edition

**[Affected Platforms]:** 	 	
- All Linux

**[Prerequisites]:**
- Have a new Firefox profile with the latest version of the "Firefox Narrate" add-on (0.3) custom build installed, through "about:debugging".
- You are enrolled in the "feature-passive" or "feature-active" branch.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites and navigate to the "https://en.wikipedia.org/wiki/Main_Page" website.
2. Observe the "Listen" string and the blue headset icon displayed in the Awesomebar.

**[Expected result]:**
- The "Listen" string and the blue headset icon are correctly displayed.

**[Actual result]:**
- The "Listen" string overlaps with the blue headset icon.

**[Notes]:**
- Attached is a screen shot of the issue: 
![overlap](https://user-images.githubusercontent.com/40061643/53078255-7d4b4a80-34fc-11e9-9500-43482616a42f.png)

**Comment by awallin** [comment]
@Gozala Looks like the wrong font is loaded in Linux. If it's time consuming to fix we can close as this is a small experiment.

**Comment by Gozala** [comment]
@awallin I don't have Linux machine or VM setup to test it so it's little tricky for me to tell what exactly is going on. However I don't set any fonts, font's are set in the SVG file 

https://github.com/mozilla/firefox-narrate-experiment/blob/master/listen-with-label.svg?short_path=aa94216

Specifically this piece:

```svg
<text font-family="SegoeUI, Segoe UI" font-size="13" letter-spacing="-.0590909086">
```

I would guess those fonts don't exist on linux and system default is loaded instead, which likely measures differently and hence this issue.

I think fix would require figuring out what font to use in linux and fixing SVG file accordingly.

**Comment by awallin** [comment]
Let's exclude Linux from this experiment to avoid the effort of debugging this and other issues. Mac and Windows will provide a large enough sample size.

**Comment by Softvision-RemusDranca** [comment]
@awallin, can you please reply to the initial PI request stating that Linux will be out of scope for this study? Thank you!

**Comment by awallin** [comment]
@Softvision-RemusDranca Where/how do I make that update? My initial request was made in email. Should I respond to that to indicate Linux is out of scope?

**Comment by Softvision-RemusDranca** [comment]
@awallin I think that updating the PHD and the Experimenter card are more than enough. Thank you!
