### ISSUE TITLE
The doorhanger is wrongly redisplayed after clicking the "Toggle Reader View" button.

### ISSUE THREAD

**Issue by Softvision-PatriciuPop** [mozilla/firefox-narrate-experiment#9]
[Affected versions]:
- Firefox Dev Edition Version 66.0b9, Build ID 20190218131312
- Firefox Release Unbranded Version 65.0.1, Build ID 20190211233335

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- The firefox_listen_study-0.3 build is installed.
- Enrolled in the feature-active branch.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites and navigate to a Wikipedia article.
2. Click the "Toggle Reader View" button.
3. Click the "Toggle Reader View" button again to exit Reader View mode and observe the behavior.

[Expected result]:
- The Wikipedia article is loaded in the default view mode.

[Actual result]:
- The Wikipedia article is loaded the default view mode and the doorhanger is redisplayed.

[Notes]:
- Even if the user doesn't interact with the doorhanger itself, clicking the Toggle Reader View / Listen button should prevent the doorhanger from appearing again.
- Clicking the "Toggle Reader View" button dismisses the doorhanger, without entering Reader View Mode.
- I have attached a screen recording of the issue:
![fxnarrate_doorhanger](https://user-images.githubusercontent.com/40393891/53093914-623f0180-3521-11e9-9caf-7012579b83ca.gif)

**Comment by awallin** [comment]
@Gozala I believe this will be solved when you implement detection for a previous interaction with the doorhanger?

**Comment by Softvision-PatriciuPop** [comment]
I have verified that this issue is no longer reproducible using firefox-listen-study@shield.mozilla.org-0.4-signed-testing.xpi on Windows 10 x64 and Mac 10.14.2 using Firefox Unbranded Beta Version 66.0b12, Build ID 20190228180200.
